### ISSUE TITLE
ajout de code 

### ISSUE THREAD

**Issue by royaljacques** [HiroshimaTeam/BasePlugin-HiroTeam#1]
ne faut t'il pas mettre
class Main extends Pluginbase implement Listener {
}
???de plus vous pouvez mettre le onEnable ainsi que le registerEvent($this, $this)

**Comment by HiroshimaTeam** [comment]
Salut, l'interface Listenner n'est pas obligé d'être implémenté ni aucune autre methode

L'utilisation du Listenner se fait uniquement si on utilise des méthodes d'injection d'événement dans la class mais dans ma pratique, je préfère séparer mes fichiers

La seule chose qui est obligatoire et qui en soit est logique puisqu'elle permet la communication des plugins c'est l'héritage de PluginBase

WillyDuGang
